import Card from "@/components/Card";
import Cards from "@/components/Cards";
import Head from "next/head";

export default function Basic() {
  const codes = [
    `
gsap
  .timeline({ paused: true })
  .from('.timelines__img._bg', { opacity: 0, duration: 1 })
  .from('.timelines__img._title', { opacity: 0, scale: 0, duration: 1, ease: 'back' })
  .from('.timelines__img._fred', { yPercent: 150, stagger: 0.1, ease: 'back' }, 'freds')
  .from('.timelines__img._time', { xPercent: 100, duration: 0.4 }, '<')
    `,
    `
function sum(a, b) {
  return a + b;
}

sum();
    `,
    `
gsap
  .timeline({ paused: true })
  .from('.timelines__img._bg', { opacity: 0, duration: 1 })
  .from('.timelines__img._title', { opacity: 0, scale: 0, duration: 1, ease: 'back' })
  .from('.timelines__img._fred', { yPercent: 150, stagger: 0.1, ease: 'back' }, 'freds')
  .from('.timelines__img._time', { xPercent: 100, duration: 0.4 }, '<')
    `,
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cards>
        {codes.map((code, index) => (
          <Card code={code} key={index} />
        ))}
      </Cards>
    </>
  );
}
