import Card from "@/components/Card";
import Cards from "@/components/Cards";
import Head from "next/head";

export default function Basic() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cards>
        <Card />
        <Card />
        <Card />
      </Cards>
    </>
  );
}
